import type { Metadata } from 'next';
import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

import { Providers } from '@/providers/Providers';
import { Toaster } from '@/components/ui/sonner';
import { Modals } from '@/components/Modal/Modals';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-blue-100/40 antialiased overflow-x-hidden`}
        >
          <Providers>{children}</Providers>
          <Toaster />
          <Modals />
        </body>
      </html>
    </SessionProvider>
  );
}
