import type { Metadata } from 'next';
import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

import { Providers } from '@/providers/Providers';
import { Toaster } from '@/components/ui/sonner';
import { Modals } from '@/components/Modal/Modals';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Canva Clone',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/svg/logo.svg',
        type: 'image/svg+xml',
      },
      {
        url: '/favicon.ico',
        sizes: '32x32',
        type: 'image/x-icon',
      },
    ],
    shortcut: '/favicon.ico',
    apple: '/svg/logo.svg',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-blue-100/40 antialiased overflow-x-hidden`}
      >
        <SessionProvider session={session}>
          <Providers>
            {children}
            <Toaster />
            <Modals />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
